### PR TITLE
Error wrapping cleanup

### PR DESCRIPTION
**Pull request by apexskier**
This cleans up error wrapping in the codebase to use the more modern `errors.Wrap` pattern (`"%w"`). The long term benefit of this is to allow deep checking of error types, but it also sets better conformance with idiomatic go standards.

More reading:
- https://blog.golang.org/go1.13-errors
- https://golang.org/doc/effective_go#errors
- https://staticcheck.io/docs/checks#ST1005

### CODE REVIEW

**Review by chrisdostert — APPROVED** [review]
Awesome

**Comment by apexskier** [comment]
Ugh, following the suggestion here - https://github.com/opctl/opctl/pull/884#issuecomment-799303316, I'm hitting cloudfront errors since tests make real network connections.
opctl — -bash — bash - Terminal - 2021-03-15 at 12 57 42

**Comment by apexskier** [comment]
Those cloudfront errors are showing up in the github action as well. Here's a start at avoiding them - https://github.com/opctl/opctl/pull/889

**Comment by chrisdostert** [comment]
> Ugh, following the suggestion here - [#884 (comment)](https://github.com/opctl/opctl/pull/884#issuecomment-799303316), I'm hitting cloudfront errors since tests make real network connections.
> opctl — -bash — bash - Terminal - 2021-03-15 at 12 57 42

It looks like there was an outage earlier that's fixed now

**Pull request merged**
